spring:
  application:
    name: sast
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sast_readtrack?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sast.sastreadtrack.entity
  configuration.map-underscore-to-camel-case: true

server:
  port: 8080

